[package]
name = "replacinator"
version = "0.1.0"
authors = ["Daniel McNab <36049421+DJMcNab@users.noreply.github.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
